// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9GrDbYwHMiZcN_ZYq1oP_SHgZ72xo2ak',
    appId: '1:494961060187:web:f447dd805fa12f4afad27e',
    messagingSenderId: '494961060187',
    projectId: 'ksquare-ad-listing',
    authDomain: 'ksquare-ad-listing.firebaseapp.com',
    storageBucket: 'ksquare-ad-listing.appspot.com',
    measurementId: 'G-6Q44C5H9D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO214d_U-8SPrEa1zDvPWy78Qg_LGamg8',
    appId: '1:494961060187:android:e58002d7619a9cbafad27e',
    messagingSenderId: '494961060187',
    projectId: 'ksquare-ad-listing',
    storageBucket: 'ksquare-ad-listing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkuT_0QHakvoGIbZnULqb4DIHHV3JZU78',
    appId: '1:494961060187:ios:b08a5b954d0942dcfad27e',
    messagingSenderId: '494961060187',
    projectId: 'ksquare-ad-listing',
    storageBucket: 'ksquare-ad-listing.appspot.com',
    iosClientId: '494961060187-elfkgagu10guqamdvjgsr58adl1avi8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.itkProjectClassifiedApp',
  );
}
